@startuml

actor EMP as "Employee"

rectangle Database

rectangle "HR System" {
    usecase UC4 as "Get countries
    by population"

    usecase UCa as "Print country report"

    EMP - UC4
    UC4 ..> UCa : include
    UC4 - Database
}

@enduml